---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: httpbin
  namespace: tyk
spec:
  tykOAS:
    configmapRef:
      name: httpbin
      keyName: httpbin.json
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: tyk
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: tyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - image: carlostyk/httpbin-otel
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: "HttpBin"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tyk-otel-collector-opentelemetry-collector.tyk.svc:4318"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
