apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin
  namespace: tyk
data:
  httpbin.json: |-
    {
      "info": {
        "title": "httpbin",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "components": {},
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "HR API",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/hrapi/"
          }
        },
        "upstream": {
          "url": "http://httpbin-svc.tyk.svc:8000"
        }
      }
    }
